
--LAB2_A
SELECT *FROM DEPOSIT
SELECT *FROM BORROW
SELECT *FROM CUSTOMERS
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
SELECT LOANNO,AMOUNT FROM BORROW
SELECT *FROM BORROW WHERE BNAME='ANDHERI'
SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106
SELECT CNAME FROM BORROW WHERE AMOUNT>5000
SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-01'
SELECT CNAME FROM DEPOSIT WHERE ACTNO<105
SELECT CNAME FROM CUSTOMERS WHERE BNAME='NAGPUR' OR BNAME='DELHI'
SELECT CNAME FROM CUSTOMERS WHERE BNAME IN('NAGPUR','DELHI')
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
SELECT * FROM DEPOSIT WHERE BNAME<>'ANDHERI'
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G.ROAD' AND ACTNO<104



--LAB2_B
SELECT TOP 5 *FROM DEPOSIT
SELECT TOP 3* FROM DEPOSIT WHERE AMOUNT>1000
SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'
SELECT DISTINCT CNAME FROM CUSTOMERS
SELECT DISTINCT BNAME FROM BRANCH


--LAB2_C
SELECT TOP 50 PERCENT *FROM BORROW
SELECT TOP 10 PERCENT *FROM DEPOSIT
SELECT TOP 25 PERCENT *FROM DEPOSIT WHERE AMOUNT>5000
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
SELECT DISTINCT CNAME,CITY FROM CUSTOMERS
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
SELECT AMOUNT,AMOUNT+AMOUNT*0.1 AS [NEW COLUMN]FROM BORROW
SELECT *FROM BORROW WHERE LOANNO%2=0
SELECT *FROM BORROW WHERE LOANNO%2<>0


