
--LAB1
CREATE TABLE DEPOSIT(
ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2),
ADATE DATETIME
);

CREATE TABLE BRANCH(
BNAME VARCHAR(50),
CITY VARCHAR(50),
);

CREATE TABLE CUSTOMERS(
CNAME VARCHAR(50),
CITY VARCHAR(50),
);

CREATE TABLE BORROW(
LOANNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2)
);


INSERT INTO DEPOSIT VALUES(101,'ANIL','VRCE', 1000.00,'1995-03-01')
INSERT INTO DEPOSIT VALUES(102,'SUNIL','AJNI',5000.00,'1996-01-04')
INSERT INTO DEPOSIT VALUES(103,'MEHUL','KAROLBAGH',3500.00,'1995-11-17')
INSERT INTO DEPOSIT VALUES(104,'MADHURI','CHANDI',1200.00,'1995-12-17')
INSERT INTO DEPOSIT VALUES(105,'PRAMOD','M.G. ROAD',3000.00,'1996-03-27')
INSERT INTO DEPOSIT VALUES(106,'SANDIP','ANDHERI',2000.00,'1996-03-31')
INSERT INTO DEPOSIT VALUES(107,'SHIVANI','VIRAR',1000.00,'1955-09-05')
INSERT INTO DEPOSIT VALUES(108,'KRANTI','NEHRU PLACE',5000.00,'1995-07-02')
INSERT INTO DEPOSIT VALUES(109,'MINU','POWAI',7000.00,'1995-08-10')


INSERT INTO BORROW VALUES('VRCE','NAGPUR')
INSERT INTO BORROW VALUES('AJNI','NAGPUR')
INSERT INTO BORROW VALUES('KAROLBAGH','DELHI')
INSERT INTO BORROW VALUES('CHANDI','DELHI')
INSERT INTO BORROW VALUES('DHARAMPETH','NAGPUR')
INSERT INTO BORROW VALUES('M.G.ROAD','BANGLORE')
INSERT INTO BORROW VALUES('ANDHERI','BOMBAY')
INSERT INTO BORROW VALUES('VIRAR','BOMBAY')
INSERT INTO BORROW VALUES('NEHRU PLACE','DELHI')
INSERT INTO BORROW VALUES('POWAI','BOMBAY')


INSERT INTO CUSTOMERS VALUES('ANIL','CALCUTTA')
INSERT INTO CUSTOMERS VALUES('SUNIL','DELHI')
INSERT INTO CUSTOMERS VALUES('MEHUL','BARODA')
INSERT INTO CUSTOMERS VALUES('MANDAR','PATNA')
INSERT INTO CUSTOMERS VALUES('MADHURI','NAGPUR')
INSERT INTO CUSTOMERS VALUES('PRAMOD','NAGPUR')
INSERT INTO CUSTOMERS VALUES('SANDIP','SURAT')
INSERT INTO CUSTOMERS VALUES('SHIVANI','BOMBAY')
INSERT INTO CUSTOMERS VALUES('KRANTI','BOMBAY')
INSERT INTO CUSTOMERS VALUES('NAREN','BOMBAY')


INSERT INTO BORROW VALUES(201,'ANIL','VRCE',1000.00)
INSERT INTO BORROW VALUES(206,'MEHUL','AJNI',5000.00)
INSERT INTO BORROW VALUES(311,'SUNIL','DHARAMPETH',3000.00)
INSERT INTO BORROW VALUES(321,'MADHURI','ANDHERI',2000.00)
INSERT INTO BORROW VALUES(375,'PRAMOD','VIRAR',8000.00)
INSERT INTO BORROW VALUES(481,'KRANTI','NEHRU PLACE',3000.00)