CREATE TABLE STU_INFO(
RNO INT,
NAME VARCHAR(50),
BRANCH VARCHAR(20)
);

CREATE TABLE RESULT(
RNO INT,
SPI DECIMAL(8,2),
);

CREATE TABLE EMPLOYEE_MASTER(
EMPLOYEENO VARCHAR(20),
NAME VARCHAR(50),
MANAGERNO VARCHAR(20)
);

SELECT * FROM STU_INFO
SELECT * FROM RESULT
SELECT * FROM EMPLOYEE_MASTER

INSERT INTO STU_INFO VALUES(101,'Raju','CE')
INSERT INTO STU_INFO VALUES(102,'Amit','CE')
INSERT INTO STU_INFO VALUES(103,'Sanjay','ME')
INSERT INTO STU_INFO VALUES(104,'Neha','EC')
INSERT INTO STU_INFO VALUES(105,'Meera','EE')
INSERT INTO STU_INFO VALUES(106,'Mahesh','ME')



INSERT INTO RESULT VALUES(101,8.8),(102,9.2),(103,7.6),(104,8.2),(105,7.0),(107,8.9)

INSERT INTO EMPLOYEE_MASTER VALUES('E01','Tarun',NULL),
('E02','Rohan','E02'),('E03','Priya','E01'),('E04','Milan','E03'),('E05','Jay','E01'),('E06','Anjana','E04')



---PART_A

SELECT * FROM STU_INFO,RESULT

SELECT * FROM STU_INFO INNER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO 

SELECT * FROM STU_INFO LEFT OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO

SELECT * FROM STU_INFO RIGHT OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO

SELECT * FROM STU_INFO FULL OUTER JOIN RESULT ON STU_INFO.RNO=RESULT.RNO

SELECT S.RNO, S.NAME,S.BRANCH,R.SPI FROM STU_INFO S JOIN RESULT R ON S.RNO=R.RNO 

SELECT * FROM STU_INFO JOIN RESULT ON STU_INFO.RNO=RESULT.RNO WHERE STU_INFO.BRANCH='CE'

SELECT * FROM STU_INFO  JOIN RESULT ON STU_INFO.RNO=RESULT.RNO WHERE STU_INFO.BRANCH <> 'EC'

SELECT AVG(R.SPI),S.BRANCH FROM STU_INFO S JOIN RESULT R ON S.RNO=R.RNO GROUP BY BRANCH

SELECT AVG(R.SPI),S.BRANCH FROM STU_INFO S JOIN RESULT R ON S.RNO=R.RNO WHERE S.BRANCH='CE' OR S.BRANCH='ME' GROUP BY BRANCH



----PART B----
SELECT AVG(R.SPI),S.BRANCH FROM STU_INFO S JOIN RESULT R ON S.RNO=R.RNO GROUP BY S.BRANCH ORDER BY AVG(R.SPI)

SELECT MAX(R.SPI),S.BRANCH FROM STU_INFO S JOIN RESULT R ON S.RNO=R.RNO GROUP BY S.BRANCH ORDER BY MAX(R.SPI)


----PART C---

SELECT E.NAME,E.MANAGERNO,M.NAME FROM EMPLOYEE_MASTER E LEFT OUTER JOIN EMPLOYEE_MASTER M ON E.MANAGERNO=M.MANAGERNO