--LAB_7  PART-A


CREATE TABLE EMP(
EID INT,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(8,2),
JOININGDATE DATETIME,
CITY VARCHAR(50)
);

INSERT INTO EMP VALUES(101,'Rahul','Admin',56000,'1990-Jan-1','Rajkot')
INSERT INTO EMP VALUES(102,'Hardik','IT',18000,'1990-Sep-25','Ahmedabad')
INSERT INTO EMP VALUES(103,'Bhavin','HR',25000,'1991-May-14','Baroda')
INSERT INTO EMP VALUES(104,'Bhoomi','Admin',39000,'1991-Feb-08','Rajkot')
INSERT INTO EMP VALUES(105,'Rohit','IT',17000,'1990-Jul-23','Jamnagar')
INSERT INTO EMP VALUES(106,'Priya','IT',9000,'1990-Oct-18','Ahmedabad')
INSERT INTO EMP VALUES(107,'Bhoomi','HR',34000,'1991-Dec-25','Rajkot')
 SELECT *FROM EMP

SELECT MAX(SALARY) AS MAXIMUM_SALARY,MIN(SALARY) AS MINIMUM_SALARY FROM EMP 

SELECT COUNT(SALARY) AS TOTAL_SAL,AVG(SALARY) AS AVG_SALARY FROM EMP

SELECT COUNT(EID) AS TOTAL_EMP FROM EMP

SELECT MAX(SALARY) AS HIGHEST_SALARY FROM EMP WHERE CITY='RAJKOT'

SELECT MAX(SALARY) AS HIGHEST_SALARY FROM EMP WHERE DEPARTMENT='IT'

SELECT COUNT(EID) AS JOINING_DATE FROM EMP WHERE JOININGDATE>'1991-02-08'

SELECT AVG(SALARY) AS AVG_SALARY FROM EMP WHERE DEPARTMENT='ADMIN'

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMP WHERE DEPARTMENT='HR'

SELECT COUNT(DISTINCT CITY) FROM EMP

SELECT COUNT(DISTINCT DEPARTMENT) FROM EMP

SELECT MIN(SALARY) AS MIN_SALARY FROM EMP WHERE CITY='Ahmedabad'

SELECT MAX(SALARY) AS MAX_SALARY FROM EMP GROUP BY CITY

SELECT MIN(SALARY) AS MIN_SALARY FROM EMP GROUP BY DEPARTMENT

SELECT COUNT(EID) FROM EMP GROUP BY CITY

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMP GROUP BY DEPARTMENT

SELECT AVG(SALARY) FROM EMP GROUP BY DEPARTMENT

--PART-B

SELECT COUNT(EID) AS TOTAL_EMPLOYEE FROM EMP WHERE CITY='RAJKOT'

SELECT MAX(SALARY)-MIN(SALARY) AS DIFFERENCE FROM EMP 

SELECT  COUNT(EID) FROM EMP WHERE JOININGDATE<'1991-01-01'

--PART C
SELECT COUNT(EID) AS TOTAL_EMPLOYEE FROM EMP WHERE CITY='RAJKOT' OR CITY ='BARODA'

SELECT COUNT(EID) FROM EMP WHERE JOININGDATE<'1991-01-01' AND DEPARTMENT='IT'

SELECT COUNT(SALARY) AS TOTAL_SALARY FROM EMP GROUP BY JOININGDATE 

SELECT MAX(SALARY) AS MAX_SAL FROM EMP WHERE CITY LIKE'R%' GROUP BY DEPARTMENT
