--LAB 3_A


CREATE TABLE CRICKET(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO CRICKET VALUES('Sachin Tendulkar','Mumbai',30)
INSERT INTO CRICKET VALUES('Rahul Dravid','Bombay',35)
INSERT INTO CRICKET VALUES('M.S.Dhoni','Jharkhand',31)
INSERT INTO CRICKET VALUES('Suresh Raina','Gujarat',30)

SELECT *INTO WORLDCUP FROM CRICKET
SELECT *FROM WORLDCUP

SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=0
SELECT *FROM T20

SELECT *INTO IPL FROM CRICKET WHERE 1=0
SELECT *FROM IPL


--LAB 3_B
CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);


INSERT INTO CRICKET VALUES('Jay Patel','Rajkot',30)
INSERT INTO CRICKET VALUES('Rahul Dave','Baroda',35)
INSERT INTO CRICKET VALUES('Jeet Patel','Surat',31)
INSERT INTO CRICKET VALUES('Vijay Raval ','Rajkot',30)


SELECT *INTO Employee_detaiL FROM EMPLOYEE

SELECT NAME,CITY INTO Employee_data FROM EMPLOYEE WHERE 1=0

SELECT *INTO Employee_info FROM EMPLOYEE WHERE 1=0


--LAB 3_C

INSERT INTO Employee_info SELECT * FROM EMPLOYEE WHERE CITY='RAJKOT'
INSERT INTO Employee_info SELECT * FROM EMPLOYEE WHERE AGE>32







--LAB 3_UPDATE OPT


UPDATE DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000
SELECT *FROM DEPOSIT

UPDATE BORROW SET BNAME='C.G.ROAD' WHERE CNAME='ANIL'
SELECT *FROM BORROW WHERE BNAME='C.G.ROAD'

UPDATE DEPOSIT SET ACTNO=111 , AMOUNT='5000' WHERE CNAME='SANDIP'
SELECT *FROM DEPOSIT WHERE CNAME='SANDIP'

UPDATE DEPOSIT SET  AMOUNT='7000' WHERE CNAME='KRANTI'
SELECT *FROM DEPOSIT WHERE CNAME='KRANTI'

UPDATE BRANCH SET BNAME='ANDHERI WEST' WHERE BNAME='ANDHERI'
SELECT *FROM BRANCH WHERE BNAME='ANDHERI WEST'

UPDATE DEPOSIT SET BNAME='NEHRU PALACE' WHERE CNAME='MEHUL'
SELECT *FROM DEPOSIT WHERE BNAME='NEHRU PALACE'

UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO BETWEEN 103 AND 107
SELECT *FROM DEPOSIT WHERE ACTNO BETWEEN 103 AND 107

UPDATE DEPOSIT SET ADATE='1995-04-01' WHERE CNAME='ANIL'
SELECT *FROM DEPOSIT WHERE ADATE='1995-04-01'

UPDATE DEPOSIT SET AMOUNT=10000 WHERE CNAME='MINU'
SELECT *FROM DEPOSIT WHERE AMOUNT=10000

UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-04-01' WHERE CNAME='PRAMOD'
SELECT *FROM DEPOSIT WHERE CNAME='PRAMOD'




--LAB 3_B

UPDATE BORROW SET AMOUNT=AMOUNT+AMOUNT*0.1
SELECT AMOUNT FROM BORROW 

UPDATE DEPOSIT SET AMOUNT=AMOUNT+AMOUNT*0.2
SELECT *FROM DEPOSIT



--LAB 3_C

UPDATE BORROW SET AMOUNT=NULL WHERE LOANNO=321
SELECT *FROM DEPOSIT

UPDATE BORROW SET BNAME=NULL WHERE CNAME='KRANTI'
SELECT *FROM BORROW WHERE CNAME='KRANTI'

SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

SELECT CNAME FROM BORROW WHERE BNAME IS NOT NULL

UPDATE BORROW SET AMOUNT=5000,BNAME='VRCE',CNAME='DARSHAN' WHERE LOANNO=481
SELECT* FROM BORROW WHERE LOANNO=481

UPDATE DEPOSIT SET ADATE='2021-01-01' WHERE AMOUNT<2000
SELECT* FROM DEPOSIT

UPDATE DEPOSIT SET ADATE=NULL,BNAME='ANDHERI' WHERE ANO=110









