---Lab 9----

----part A----

create table STUDENT_DATA(
no int,
Name varchar(50),
City varchar(50),
DID int
);

select * from STUDENT_DATA


create table ACADEMIC(
Rno int,
SPI Decimal(8,2),
Bklog int,
);

select * from ACADEMIC


create table DEPARTMENT(
DID int,
DName varchar(50),
);

select * from DEPARTMENT


insert into STUDENT_DATA values (101,'Raju','Rajkot',10),(102,'Amit','Ahmedabad',20),(103,'Sanjay','Baroda',40),(104,'Neha','Rajkot',20),(105,'Meera','Ahmedabad',30),(106,'Mahesh','Baroda',10)

insert into ACADEMIC values (101,8.8,0),(102,9.2,2),(103,7.6,1),(104,8.2,4),(105,7.0,2),(106,8.9,3)

insert into DEPARTMENT values (10,'Computer'),(20,'Electrical'),(30,'Mechanical'),(40,'Civil')


select Name from STUDENT_DATA where DID=(select DID from DEPARTMENT where DName='Computer')

select Name from STUDENT_DATA where no in(select Rno from ACADEMIC where SPI>8)

select * from STUDENT_DATA where DID =(select DID from DEPARTMENT where DName='Computer') and City='Rajkot'

select count(no) from STUDENT_DATA where DID=(select DID from DEPARTMENT where DName='Electrical')

select Name from STUDENT_DATA where no in (select Rno from ACADEMIC where spi=(select max(spi) from ACADEMIC))

select name from STUDENT_DATA where no in (select Rno from ACADEMIC where Bklog>1)



--PART B
--1
SELECT NAME FROM STUDENT_DATA
WHERE DID 
IN (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER' OR
DNAME='MECHANICAL')

--2
SELECT NAME FROM STUDENT_DATA
WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE 
DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL'))

--PART C
--1
SELECT NAME FROM  STUDENT_DATA
WHERE NO IN (SELECT RNO FROM ACADEMIC  WHERE SPI>9) AND  DID=(SELECT DID FROM DEPARTMENT WHERE DNAME ='ELECTRICAL')

--2
SELECT name
FROM STUDENT_DATA
WHERE spi = (
    SELECT MAX(spi)
    FROM ACADEMIC
    WHERE spi < (
        SELECT MAX(spi)
        FROM ACADEMIC
    )
);


--3
SELECT CITY FROM STUDENT_DATA
WHERE NO= 
(SELECT RNO FROM ACADEMIC WHERE SPI = 9.2) 
AND 
DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME IN (SELECT DNAME FROM DEPARTMENT GROUP BY DNAME))






--SET OPERATOR
--PART A
CREATE TABLE COMPUTER(
	ROLLNO INT,
	NAME VARCHAR(20)
);
 
 INSERT INTO COMPUTER VALUES(101,'AJAY')
 INSERT INTO COMPUTER VALUES(109,'HARESH')
 INSERT INTO COMPUTER VALUES(115,'MANISH')

 SELECT * FROM COMPUTER

 CREATE TABLE ELECTRICAL(
	ROLLNO INT,
	NAME VARCHAR(20)
 );

 INSERT INTO ELECTRICAL VALUES(105,'AJAY'),
							  (107,'MAHESH'),
							  (115,'MANISH')
SELECT * FROM ELECTRICAL

--1
SELECT Name FROM COMPUTER
UNION
SELECT Name FROM ELECTRICAL;

--2
SELECT Name FROM COMPUTER
UNION ALL
SELECT Name FROM ELECTRICAL;

--3
SELECT Name FROM COMPUTER
INTERSECT
SELECT Name FROM ELECTRICAL;

--4
SELECT Name FROM COMPUTER
EXCEPT
SELECT Name FROM ELECTRICAL;

--5
SELECT Name FROM ELECTRICAL
EXCEPT
SELECT Name FROM COMPUTER;

--6
SELECT * FROM COMPUTER
UNION ALL
SELECT * FROM ELECTRICAL;

--7
SELECT * FROM COMPUTER
INTERSECT
SELECT * FROM ELECTRICAL;


-----------Part - B:----------
CREATE TABLE EMP_DATA(
		EID INT,
		NAME VARCHAR(20)
	);

INSERT INTO EMP_DATA VALUES (1,'AJAY'),
							(9,'HARESH'),
							(5,'MANISH')

CREATE TABLE CUSTOMER(
		CID INT,
		NAME VARCHAR(20)
	);

INSERT INTO CUSTOMER VALUES (5,'AJAY'),
							(7,'MAHESH'),
							(5,'MANISH')

--1
SELECT NAME FROM EMP_DATA
UNION
SELECT NAME FROM CUSTOMER

--2
SELECT NAME FROM EMP_DATA
UNION ALL
SELECT NAME FROM CUSTOMER

--3
SELECT NAME FROM EMP_DATA
INTERSECT
SELECT NAME FROM CUSTOMER

--4
SELECT NAME FROM EMP_DATA
EXCEPT
SELECT NAME FROM CUSTOMER

--5
SELECT NAME FROM CUSTOMER
EXCEPT
SELECT NAME FROM EMP_DATA

----------------Part - C:-----------------

--1
SELECT NAME, EID FROM EMP_DATA
UNION
SELECT NAME, CID FROM CUSTOMER

--2
SELECT NAME,EID FROM EMP_DATA
UNION ALL
SELECT NAME,CID FROM CUSTOMER

--3
SELECT NAME,EID FROM EMP_DATA
INTERSECT
SELECT NAME,CID FROM CUSTOMER

--4
SELECT NAME,EID FROM EMP_DATA
EXCEPT
SELECT NAME,CID FROM CUSTOMER

--5
SELECT NAME,CID FROM CUSTOMER
EXCEPT
SELECT NAME,EID FROM EMP_DATA