--LAB_8

CREATE TABLE SALES_DATA(
REGION VARCHAR(50),
PRODUCT VARCHAR(50),
SALES_AMOUNT DECIMAL(8,2),
YEAR INT
);

INSERT INTO SALES_DATA VALUES('North America','Watch',1500,'2023')
INSERT INTO SALES_DATA VALUES('Europe','Mobile',1200,'2023')
INSERT INTO SALES_DATA VALUES('Asia','Watch',1800,'2023')
INSERT INTO SALES_DATA VALUES('North America','TV',900,'2024')
INSERT INTO SALES_DATA VALUES('Europe','Watch',2000,'2024')
INSERT INTO SALES_DATA VALUES('Asia','Mobile',1000,'2024')
INSERT INTO SALES_DATA VALUES('North America','Mobile',1600,'2023')
INSERT INTO SALES_DATA VALUES('Europe','TV',1500,'2023')
INSERT INTO SALES_DATA VALUES('Asia','TV',1100,'2024')
INSERT INTO SALES_DATA VALUES('North America','Watch',1700,'2024')

SELECT *FROM SALES_DATA


SELECT SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY REGION

SELECT AVG(SALES_AMOUNT) AS AVERGAGE_SALES FROM SALES_DATA GROUP BY PRODUCT

SELECT MAX(SALES_AMOUNT) AS MAXIMUM_SALES FROM SALES_DATA GROUP BY YEAR

SELECT MIN(SALES_AMOUNT) AS MINIMUM_SALES FROM SALES_DATA GROUP BY YEAR,REGION

SELECT COUNT(PRODUCT) AS TOTAL_COUNT FROM SALES_DATA GROUP BY REGION

SELECT SUM(SALES_AMOUNT) AS SUM_AMOUNT FROM SALES_DATA GROUP BY YEAR,PRODUCT

SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000

SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVERAGE_SALES FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000

SELECT YEAR,MAX(SALES_AMOUNT) AS MAXIMUM_SALES FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)>500

SELECT REGION,COUNT(DISTINCT PRODUCT) AS REGION FROM SALES_DATA GROUP BY REGION HAVING COUNT(DISTINCT PRODUCT)>=3 

SELECT YEAR,MIN(SALES_AMOUNT) AS MINIMUN_SALES FROM SALES_DATA GROUP BY YEAR HAVING MIN(SALES_AMOUNT)<1000

SELECT REGION,SUM(SALES_AMOUNT) AS TOTA_SALES FROM SALES_DATA WHERE YEAR='2023' GROUP BY REGION ORDER BY SUM(SALES_AMOUNT)

--PART B

SELECT YEAR,COUNT(PRODUCT) FROM SALES_DATA GROUP BY YEAR,REGION ORDER BY YEAR,REGION

SELECT REGION,MAX(SALES_AMOUNT) AS MAXIMUM_AMOUNT FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION

SELECT YEAR,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)<1000 ORDER BY YEAR DESC

SELECT	TOP 3 SUM(SALES_AMOUNT) AS REGION FROM SALES_DATA WHERE YEAR=2024 GROUP BY REGION 

--PART C

SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVERAGE_SALES FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000 ORDER BY PRODUCT

SELECT REGION,YEAR,COUNT(PRODUCT)FROM SALES_DATA GROUP BY REGION,YEAR HAVING  COUNT(PRODUCT)>5 ORDER BY REGION,YEAR

SELECT AVG(SALES_AMOUNT),YEAR FROM SALES_DATA WHERE YEAR=2023 GROUP BY SALES_AMOUNT,YEAR HAVING AVG(SALES_AMOUNT)>1500 ORDER BY SALES_AMOUNT,YEAR DESC

SELECT COUNT(PRODUCT),REGION FROM SALES_DATA GROUP BY PRODUCT,REGION HAVING  COUNT(PRODUCT)>1

SELECT MAX(SALES_AMOUNT),REGION AS MAXIMUM_SALES FROM SALES_DATA GROUP BY REGION 